guests = ["Will Smith", "Ben Aflick", "Anjelina Jolie"]
print("Deear "  + (guests[0]),  "can you accept my invite for dinner")
print("Deear "  + (guests[1]),  "can you accept my invite for dinner")
print("Deear "  + (guests[2]),  "can you accept my invite for dinner")
guests.pop(1)
guests.insert(1, "Katrin")
print("Deear "  + (guests[0]),  "can you accept my invite for dinner")
print("Deear "  + (guests[1]),  "can you accept my invite for dinner")
print("Deear "  + (guests[2]),  "can you accept my invite for dinner")
print(guests) 